version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: administrador-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mi_contrasena # para el usuario root
      MYSQL_DATABASE: biblioteca  # base de datos automaticos
      MYSQL_USER: usuario_dev # usuario desarrollo
      MYSQL_PASSWORD: password_dev # clave desarrollo
    ports:
      - "3306:3306" # puerto mysql 
    volumes:
      - db_data:/var/lib/mysql # persistencia de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script de inicializaci√≥n
  # una interfaz web para mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80" # acceder al entorno web
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: mi_contrasena # clave de acceso
    depends_on:
      - db

volumes:
  db_data: